### ISSUE TITLE
Failing test_index_filter_by_created (__main__.TournamentsTestCase) - Python 2.7.14

### ISSUE THREAD

**Issue by russellvt** [russ-/pychallonge#14]
Looks like this test case is failing...
```
(pychallonge-2.7.14) ~/projects/russell/challonge/pychallonge$ CHALLONGE_USER=russellvt CHALLONGE_KEY=$(cat ../api.key) python ./tests.py
...........EE......
======================================================================
ERROR: test_index_filter_by_created (__main__.TournamentsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests.py", line 65, in test_index_filter_by_created
    created_after=datetime.datetime.now().date() - datetime.timedelta(days=1))
  File "/home/russell/projects/russell/challonge/pychallonge/challonge/tournaments.py", line 6, in index
    return api.fetch_and_parse("GET", "tournaments", **params)
  File "/home/russell/projects/russell/challonge/pychallonge/challonge/api.py", line 79, in fetch_and_parse
    doc = ElementTree.parse(fetch(method, uri, params_prefix, **params))
  File "/home/russell/projects/russell/challonge/pychallonge/challonge/api.py", line 63, in fetch
    response = opener.open(req)
  File "/home/russell/.pyenv/versions/2.7.14/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/russell/.pyenv/versions/2.7.14/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/russell/.pyenv/versions/2.7.14/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/home/russell/.pyenv/versions/2.7.14/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/russell/.pyenv/versions/2.7.14/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request
```

**Comment by russellvt** [comment]
Thanks... I've merged your stuff in to mine, and I'll go from there.

**Comment by ZEDGR** [comment]
I am actively maintain my fork. So if you find any bug or something to improve please make a PR on my repo or mention it and I will fix/implement it.
